
DROP TABLE EMP_RSA;
DROP TABLE JOBS_RSA;
DROP TABLE JOB_GRADES_RSA;
DROP TABLE JOB_HISTORY_RSA;
DROP TABLE LOCATIONS_RSA;
DROP TABLE MEMBER_RSA;
DROP TABLE PROJECTS_RSA;
DROP TABLE REGIONS_RSA;
DROP TABLE RENTAL_RSA;
DROP TABLE RESERVATION_RSA;
DROP TABLE TITLE_COPY_RSA;
DROP TABLE TITLE_RSA;
DROP TABLE WORK_RSA;

13 rows selected. 

